# coding: utf-8

from __future__ import absolute_import

import re  # noqa: F401,E501
from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.contact import Contact  # noqa: F401,E501
from models.image import Image  # noqa: F401,E501
from models.name import Name  # noqa: F401,E501
from models.person import Person  # noqa: F401,E501
from models.rateable import Rateable  # noqa: F401,E501
from models.tags import Tags  # noqa: F401,E501


class Agent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, phone: str=None, email: str=None, tags: Tags=None, name: Name=None, image: Image=None, dob: date=None, gender: str=None, cred: str=None, rateable: Rateable=None):  # noqa: E501
        """Agent - a model defined in Swagger

        :param phone: The phone of this Agent.  # noqa: E501
        :type phone: str
        :param email: The email of this Agent.  # noqa: E501
        :type email: str
        :param tags: The tags of this Agent.  # noqa: E501
        :type tags: Tags
        :param name: The name of this Agent.  # noqa: E501
        :type name: Name
        :param image: The image of this Agent.  # noqa: E501
        :type image: Image
        :param dob: The dob of this Agent.  # noqa: E501
        :type dob: date
        :param gender: The gender of this Agent.  # noqa: E501
        :type gender: str
        :param cred: The cred of this Agent.  # noqa: E501
        :type cred: str
        :param rateable: The rateable of this Agent.  # noqa: E501
        :type rateable: Rateable
        """
        self.swagger_types = {
            'phone': str,
            'email': str,
            'tags': Tags,
            'name': Name,
            'image': Image,
            'dob': date,
            'gender': str,
            'cred': str,
            'rateable': Rateable
        }

        self.attribute_map = {
            'phone': 'phone',
            'email': 'email',
            'tags': 'tags',
            'name': 'name',
            'image': 'image',
            'dob': 'dob',
            'gender': 'gender',
            'cred': 'cred',
            'rateable': 'rateable'
        }
        self._phone = phone
        self._email = email
        self._tags = tags
        self._name = name
        self._image = image
        self._dob = dob
        self._gender = gender
        self._cred = cred
        self._rateable = rateable

    @classmethod
    def from_dict(cls, dikt) -> 'Agent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Agent of this Agent.  # noqa: E501
        :rtype: Agent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phone(self) -> str:
        """Gets the phone of this Agent.


        :return: The phone of this Agent.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this Agent.


        :param phone: The phone of this Agent.
        :type phone: str
        """

        self._phone = phone

    @property
    def email(self) -> str:
        """Gets the email of this Agent.


        :return: The email of this Agent.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Agent.


        :param email: The email of this Agent.
        :type email: str
        """

        self._email = email

    @property
    def tags(self) -> Tags:
        """Gets the tags of this Agent.


        :return: The tags of this Agent.
        :rtype: Tags
        """
        return self._tags

    @tags.setter
    def tags(self, tags: Tags):
        """Sets the tags of this Agent.


        :param tags: The tags of this Agent.
        :type tags: Tags
        """

        self._tags = tags

    @property
    def name(self) -> Name:
        """Gets the name of this Agent.


        :return: The name of this Agent.
        :rtype: Name
        """
        return self._name

    @name.setter
    def name(self, name: Name):
        """Sets the name of this Agent.


        :param name: The name of this Agent.
        :type name: Name
        """

        self._name = name

    @property
    def image(self) -> Image:
        """Gets the image of this Agent.


        :return: The image of this Agent.
        :rtype: Image
        """
        return self._image

    @image.setter
    def image(self, image: Image):
        """Sets the image of this Agent.


        :param image: The image of this Agent.
        :type image: Image
        """

        self._image = image

    @property
    def dob(self) -> date:
        """Gets the dob of this Agent.


        :return: The dob of this Agent.
        :rtype: date
        """
        return self._dob

    @dob.setter
    def dob(self, dob: date):
        """Sets the dob of this Agent.


        :param dob: The dob of this Agent.
        :type dob: date
        """

        self._dob = dob

    @property
    def gender(self) -> str:
        """Gets the gender of this Agent.

        Gender of something, typically a Person, but possibly also fictional characters, animals, etc. While Male and Female may be used, text strings are also acceptable for people who do not identify as a binary gender  # noqa: E501

        :return: The gender of this Agent.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """Sets the gender of this Agent.

        Gender of something, typically a Person, but possibly also fictional characters, animals, etc. While Male and Female may be used, text strings are also acceptable for people who do not identify as a binary gender  # noqa: E501

        :param gender: The gender of this Agent.
        :type gender: str
        """

        self._gender = gender

    @property
    def cred(self) -> str:
        """Gets the cred of this Agent.


        :return: The cred of this Agent.
        :rtype: str
        """
        return self._cred

    @cred.setter
    def cred(self, cred: str):
        """Sets the cred of this Agent.


        :param cred: The cred of this Agent.
        :type cred: str
        """

        self._cred = cred

    @property
    def rateable(self) -> Rateable:
        """Gets the rateable of this Agent.


        :return: The rateable of this Agent.
        :rtype: Rateable
        """
        return self._rateable

    @rateable.setter
    def rateable(self, rateable: Rateable):
        """Sets the rateable of this Agent.


        :param rateable: The rateable of this Agent.
        :type rateable: Rateable
        """

        self._rateable = rateable
