# coding: utf-8

from __future__ import absolute_import

import re  # noqa: F401,E501
from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.address import Address  # noqa: F401,E501
from models.base_model_ import Model
from models.circle import Circle  # noqa: F401,E501
from models.city import City  # noqa: F401,E501
from models.country import Country  # noqa: F401,E501
from models.descriptor import Descriptor  # noqa: F401,E501
from models.gps import Gps  # noqa: F401,E501
from models.location import Location  # noqa: F401,E501
from models.rateable import Rateable  # noqa: F401,E501
from models.time import Time  # noqa: F401,E501


class AllOfProviderLocationsItems(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, descriptor: Descriptor=None, gps: Gps=None, address: Address=None, station_code: str=None, city: City=None, country: Country=None, circle: Circle=None, polygon: str=None, _3dspace: str=None, time: Time=None, rateable: Rateable=None):  # noqa: E501
        """AllOfProviderLocationsItems - a model defined in Swagger

        :param id: The id of this AllOfProviderLocationsItems.  # noqa: E501
        :type id: str
        :param descriptor: The descriptor of this AllOfProviderLocationsItems.  # noqa: E501
        :type descriptor: Descriptor
        :param gps: The gps of this AllOfProviderLocationsItems.  # noqa: E501
        :type gps: Gps
        :param address: The address of this AllOfProviderLocationsItems.  # noqa: E501
        :type address: Address
        :param station_code: The station_code of this AllOfProviderLocationsItems.  # noqa: E501
        :type station_code: str
        :param city: The city of this AllOfProviderLocationsItems.  # noqa: E501
        :type city: City
        :param country: The country of this AllOfProviderLocationsItems.  # noqa: E501
        :type country: Country
        :param circle: The circle of this AllOfProviderLocationsItems.  # noqa: E501
        :type circle: Circle
        :param polygon: The polygon of this AllOfProviderLocationsItems.  # noqa: E501
        :type polygon: str
        :param _3dspace: The _3dspace of this AllOfProviderLocationsItems.  # noqa: E501
        :type _3dspace: str
        :param time: The time of this AllOfProviderLocationsItems.  # noqa: E501
        :type time: Time
        :param rateable: The rateable of this AllOfProviderLocationsItems.  # noqa: E501
        :type rateable: Rateable
        """
        self.swagger_types = {
            'id': str,
            'descriptor': Descriptor,
            'gps': Gps,
            'address': Address,
            'station_code': str,
            'city': City,
            'country': Country,
            'circle': Circle,
            'polygon': str,
            '_3dspace': str,
            'time': Time,
            'rateable': Rateable
        }

        self.attribute_map = {
            'id': 'id',
            'descriptor': 'descriptor',
            'gps': 'gps',
            'address': 'address',
            'station_code': 'station_code',
            'city': 'city',
            'country': 'country',
            'circle': 'circle',
            'polygon': 'polygon',
            '_3dspace': '3dspace',
            'time': 'time',
            'rateable': 'rateable'
        }
        self._id = id
        self._descriptor = descriptor
        self._gps = gps
        self._address = address
        self._station_code = station_code
        self._city = city
        self._country = country
        self._circle = circle
        self._polygon = polygon
        self.__3dspace = _3dspace
        self._time = time
        self._rateable = rateable

    @classmethod
    def from_dict(cls, dikt) -> 'AllOfProviderLocationsItems':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllOfProviderLocationsItems of this AllOfProviderLocationsItems.  # noqa: E501
        :rtype: AllOfProviderLocationsItems
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this AllOfProviderLocationsItems.


        :return: The id of this AllOfProviderLocationsItems.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this AllOfProviderLocationsItems.


        :param id: The id of this AllOfProviderLocationsItems.
        :type id: str
        """

        self._id = id

    @property
    def descriptor(self) -> Descriptor:
        """Gets the descriptor of this AllOfProviderLocationsItems.


        :return: The descriptor of this AllOfProviderLocationsItems.
        :rtype: Descriptor
        """
        return self._descriptor

    @descriptor.setter
    def descriptor(self, descriptor: Descriptor):
        """Sets the descriptor of this AllOfProviderLocationsItems.


        :param descriptor: The descriptor of this AllOfProviderLocationsItems.
        :type descriptor: Descriptor
        """

        self._descriptor = descriptor

    @property
    def gps(self) -> Gps:
        """Gets the gps of this AllOfProviderLocationsItems.


        :return: The gps of this AllOfProviderLocationsItems.
        :rtype: Gps
        """
        return self._gps

    @gps.setter
    def gps(self, gps: Gps):
        """Sets the gps of this AllOfProviderLocationsItems.


        :param gps: The gps of this AllOfProviderLocationsItems.
        :type gps: Gps
        """

        self._gps = gps

    @property
    def address(self) -> Address:
        """Gets the address of this AllOfProviderLocationsItems.


        :return: The address of this AllOfProviderLocationsItems.
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address: Address):
        """Sets the address of this AllOfProviderLocationsItems.


        :param address: The address of this AllOfProviderLocationsItems.
        :type address: Address
        """

        self._address = address

    @property
    def station_code(self) -> str:
        """Gets the station_code of this AllOfProviderLocationsItems.


        :return: The station_code of this AllOfProviderLocationsItems.
        :rtype: str
        """
        return self._station_code

    @station_code.setter
    def station_code(self, station_code: str):
        """Sets the station_code of this AllOfProviderLocationsItems.


        :param station_code: The station_code of this AllOfProviderLocationsItems.
        :type station_code: str
        """

        self._station_code = station_code

    @property
    def city(self) -> City:
        """Gets the city of this AllOfProviderLocationsItems.


        :return: The city of this AllOfProviderLocationsItems.
        :rtype: City
        """
        return self._city

    @city.setter
    def city(self, city: City):
        """Sets the city of this AllOfProviderLocationsItems.


        :param city: The city of this AllOfProviderLocationsItems.
        :type city: City
        """

        self._city = city

    @property
    def country(self) -> Country:
        """Gets the country of this AllOfProviderLocationsItems.


        :return: The country of this AllOfProviderLocationsItems.
        :rtype: Country
        """
        return self._country

    @country.setter
    def country(self, country: Country):
        """Sets the country of this AllOfProviderLocationsItems.


        :param country: The country of this AllOfProviderLocationsItems.
        :type country: Country
        """

        self._country = country

    @property
    def circle(self) -> Circle:
        """Gets the circle of this AllOfProviderLocationsItems.


        :return: The circle of this AllOfProviderLocationsItems.
        :rtype: Circle
        """
        return self._circle

    @circle.setter
    def circle(self, circle: Circle):
        """Sets the circle of this AllOfProviderLocationsItems.


        :param circle: The circle of this AllOfProviderLocationsItems.
        :type circle: Circle
        """

        self._circle = circle

    @property
    def polygon(self) -> str:
        """Gets the polygon of this AllOfProviderLocationsItems.


        :return: The polygon of this AllOfProviderLocationsItems.
        :rtype: str
        """
        return self._polygon

    @polygon.setter
    def polygon(self, polygon: str):
        """Sets the polygon of this AllOfProviderLocationsItems.


        :param polygon: The polygon of this AllOfProviderLocationsItems.
        :type polygon: str
        """

        self._polygon = polygon

    @property
    def _3dspace(self) -> str:
        """Gets the _3dspace of this AllOfProviderLocationsItems.


        :return: The _3dspace of this AllOfProviderLocationsItems.
        :rtype: str
        """
        return self.__3dspace

    @_3dspace.setter
    def _3dspace(self, _3dspace: str):
        """Sets the _3dspace of this AllOfProviderLocationsItems.


        :param _3dspace: The _3dspace of this AllOfProviderLocationsItems.
        :type _3dspace: str
        """

        self.__3dspace = _3dspace

    @property
    def time(self) -> Time:
        """Gets the time of this AllOfProviderLocationsItems.


        :return: The time of this AllOfProviderLocationsItems.
        :rtype: Time
        """
        return self._time

    @time.setter
    def time(self, time: Time):
        """Sets the time of this AllOfProviderLocationsItems.


        :param time: The time of this AllOfProviderLocationsItems.
        :type time: Time
        """

        self._time = time

    @property
    def rateable(self) -> Rateable:
        """Gets the rateable of this AllOfProviderLocationsItems.


        :return: The rateable of this AllOfProviderLocationsItems.
        :rtype: Rateable
        """
        return self._rateable

    @rateable.setter
    def rateable(self, rateable: Rateable):
        """Sets the rateable of this AllOfProviderLocationsItems.


        :param rateable: The rateable of this AllOfProviderLocationsItems.
        :type rateable: Rateable
        """

        self._rateable = rateable
