# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.cancellation_reasons_message import CancellationReasonsMessage  # noqa: F401,E501
from models.context import Context  # noqa: F401,E501


class CancellationReasonsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, context: Context=None, message: CancellationReasonsMessage=None):  # noqa: E501
        """CancellationReasonsBody - a model defined in Swagger

        :param context: The context of this CancellationReasonsBody.  # noqa: E501
        :type context: Context
        :param message: The message of this CancellationReasonsBody.  # noqa: E501
        :type message: CancellationReasonsMessage
        """
        self.swagger_types = {
            'context': Context,
            'message': CancellationReasonsMessage
        }

        self.attribute_map = {
            'context': 'context',
            'message': 'message'
        }
        self._context = context
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'CancellationReasonsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cancellation_reasons_body of this CancellationReasonsBody.  # noqa: E501
        :rtype: CancellationReasonsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context(self) -> Context:
        """Gets the context of this CancellationReasonsBody.


        :return: The context of this CancellationReasonsBody.
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context: Context):
        """Sets the context of this CancellationReasonsBody.


        :param context: The context of this CancellationReasonsBody.
        :type context: Context
        """

        self._context = context

    @property
    def message(self) -> CancellationReasonsMessage:
        """Gets the message of this CancellationReasonsBody.


        :return: The message of this CancellationReasonsBody.
        :rtype: CancellationReasonsMessage
        """
        return self._message

    @message.setter
    def message(self, message: CancellationReasonsMessage):
        """Sets the message of this CancellationReasonsBody.


        :param message: The message of this CancellationReasonsBody.
        :type message: CancellationReasonsMessage
        """

        self._message = message
