# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.descriptor import Descriptor  # noqa: F401,E501
from models import Optionpropertiesid  # noqa: F401,E501
from models import Orderpropertiesid  # noqa: F401,E501


class CancelMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order_id: Orderpropertiesid=None, cancellation_reason_id: Optionpropertiesid=None, descriptor: Descriptor=None):  # noqa: E501
        """CancelMessage - a model defined in Swagger

        :param order_id: The order_id of this CancelMessage.  # noqa: E501
        :type order_id: Orderpropertiesid
        :param cancellation_reason_id: The cancellation_reason_id of this CancelMessage.  # noqa: E501
        :type cancellation_reason_id: Optionpropertiesid
        :param descriptor: The descriptor of this CancelMessage.  # noqa: E501
        :type descriptor: Descriptor
        """
        self.swagger_types = {
            'order_id': Orderpropertiesid,
            'cancellation_reason_id': Optionpropertiesid,
            'descriptor': Descriptor
        }

        self.attribute_map = {
            'order_id': 'order_id',
            'cancellation_reason_id': 'cancellation_reason_id',
            'descriptor': 'descriptor'
        }
        self._order_id = order_id
        self._cancellation_reason_id = cancellation_reason_id
        self._descriptor = descriptor

    @classmethod
    def from_dict(cls, dikt) -> 'CancelMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cancel_message of this CancelMessage.  # noqa: E501
        :rtype: CancelMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> Orderpropertiesid:
        """Gets the order_id of this CancelMessage.


        :return: The order_id of this CancelMessage.
        :rtype: Orderpropertiesid
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: Orderpropertiesid):
        """Sets the order_id of this CancelMessage.


        :param order_id: The order_id of this CancelMessage.
        :type order_id: Orderpropertiesid
        """
        if order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id

    @property
    def cancellation_reason_id(self) -> Optionpropertiesid:
        """Gets the cancellation_reason_id of this CancelMessage.


        :return: The cancellation_reason_id of this CancelMessage.
        :rtype: Optionpropertiesid
        """
        return self._cancellation_reason_id

    @cancellation_reason_id.setter
    def cancellation_reason_id(self, cancellation_reason_id: Optionpropertiesid):
        """Sets the cancellation_reason_id of this CancelMessage.


        :param cancellation_reason_id: The cancellation_reason_id of this CancelMessage.
        :type cancellation_reason_id: Optionpropertiesid
        """

        self._cancellation_reason_id = cancellation_reason_id

    @property
    def descriptor(self) -> Descriptor:
        """Gets the descriptor of this CancelMessage.


        :return: The descriptor of this CancelMessage.
        :rtype: Descriptor
        """
        return self._descriptor

    @descriptor.setter
    def descriptor(self, descriptor: Descriptor):
        """Sets the descriptor of this CancelMessage.


        :param descriptor: The descriptor of this CancelMessage.
        :type descriptor: Descriptor
        """

        self._descriptor = descriptor
