# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.descriptor import Descriptor  # noqa: F401,E501
from models.tags import Tags  # noqa: F401,E501
from models.time import Time  # noqa: F401,E501


class Category(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, parent_category_id: str=None, descriptor: Descriptor=None, time: Time=None, tags: Tags=None):  # noqa: E501
        """Category - a model defined in Swagger

        :param id: The id of this Category.  # noqa: E501
        :type id: str
        :param parent_category_id: The parent_category_id of this Category.  # noqa: E501
        :type parent_category_id: str
        :param descriptor: The descriptor of this Category.  # noqa: E501
        :type descriptor: Descriptor
        :param time: The time of this Category.  # noqa: E501
        :type time: Time
        :param tags: The tags of this Category.  # noqa: E501
        :type tags: Tags
        """
        self.swagger_types = {
            'id': str,
            'parent_category_id': str,
            'descriptor': Descriptor,
            'time': Time,
            'tags': Tags
        }

        self.attribute_map = {
            'id': 'id',
            'parent_category_id': 'parent_category_id',
            'descriptor': 'descriptor',
            'time': 'time',
            'tags': 'tags'
        }
        self._id = id
        self._parent_category_id = parent_category_id
        self._descriptor = descriptor
        self._time = time
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'Category':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Category of this Category.  # noqa: E501
        :rtype: Category
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Category.

        Unique id of the category  # noqa: E501

        :return: The id of this Category.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Category.

        Unique id of the category  # noqa: E501

        :param id: The id of this Category.
        :type id: str
        """

        self._id = id

    @property
    def parent_category_id(self) -> str:
        """Gets the parent_category_id of this Category.


        :return: The parent_category_id of this Category.
        :rtype: str
        """
        return self._parent_category_id

    @parent_category_id.setter
    def parent_category_id(self, parent_category_id: str):
        """Sets the parent_category_id of this Category.


        :param parent_category_id: The parent_category_id of this Category.
        :type parent_category_id: str
        """

        self._parent_category_id = parent_category_id

    @property
    def descriptor(self) -> Descriptor:
        """Gets the descriptor of this Category.


        :return: The descriptor of this Category.
        :rtype: Descriptor
        """
        return self._descriptor

    @descriptor.setter
    def descriptor(self, descriptor: Descriptor):
        """Sets the descriptor of this Category.


        :param descriptor: The descriptor of this Category.
        :type descriptor: Descriptor
        """

        self._descriptor = descriptor

    @property
    def time(self) -> Time:
        """Gets the time of this Category.


        :return: The time of this Category.
        :rtype: Time
        """
        return self._time

    @time.setter
    def time(self, time: Time):
        """Sets the time of this Category.


        :param time: The time of this Category.
        :type time: Time
        """

        self._time = time

    @property
    def tags(self) -> Tags:
        """Gets the tags of this Category.


        :return: The tags of this Category.
        :rtype: Tags
        """
        return self._tags

    @tags.setter
    def tags(self, tags: Tags):
        """Sets the tags of this Category.


        :param tags: The tags of this Category.
        :type tags: Tags
        """

        self._tags = tags
