# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model


class Country(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, code: str=None):  # noqa: E501
        """Country - a model defined in Swagger

        :param name: The name of this Country.  # noqa: E501
        :type name: str
        :param code: The code of this Country.  # noqa: E501
        :type code: str
        """
        self.swagger_types = {
            'name': str,
            'code': str
        }

        self.attribute_map = {
            'name': 'name',
            'code': 'code'
        }
        self._name = name
        self._code = code

    @classmethod
    def from_dict(cls, dikt) -> 'Country':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Country of this Country.  # noqa: E501
        :rtype: Country
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Country.

        Name of the country  # noqa: E501

        :return: The name of this Country.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Country.

        Name of the country  # noqa: E501

        :param name: The name of this Country.
        :type name: str
        """

        self._name = name

    @property
    def code(self) -> str:
        """Gets the code of this Country.

        Country code as per ISO 3166-1 and ISO 3166-2 format  # noqa: E501

        :return: The code of this Country.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Country.

        Country code as per ISO 3166-1 and ISO 3166-2 format  # noqa: E501

        :param code: The code of this Country.
        :type code: str
        """

        self._code = code
