# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model


class Document(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, url: str=None, label: str=None):  # noqa: E501
        """Document - a model defined in Swagger

        :param url: The url of this Document.  # noqa: E501
        :type url: str
        :param label: The label of this Document.  # noqa: E501
        :type label: str
        """
        self.swagger_types = {
            'url': str,
            'label': str
        }

        self.attribute_map = {
            'url': 'url',
            'label': 'label'
        }
        self._url = url
        self._label = label

    @classmethod
    def from_dict(cls, dikt) -> 'Document':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Document of this Document.  # noqa: E501
        :rtype: Document
        """
        return util.deserialize_model(dikt, cls)

    @property
    def url(self) -> str:
        """Gets the url of this Document.


        :return: The url of this Document.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this Document.


        :param url: The url of this Document.
        :type url: str
        """

        self._url = url

    @property
    def label(self) -> str:
        """Gets the label of this Document.


        :return: The label of this Document.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """Sets the label of this Document.


        :param label: The label of this Document.
        :type label: str
        """

        self._label = label
