# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.feedback_form import FeedbackForm  # noqa: F401,E501
from models.feedback_url import FeedbackUrl  # noqa: F401,E501


class Feedback(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, feedback_form: FeedbackForm=None, feedback_url: FeedbackUrl=None):  # noqa: E501
        """Feedback - a model defined in Swagger

        :param feedback_form: The feedback_form of this Feedback.  # noqa: E501
        :type feedback_form: FeedbackForm
        :param feedback_url: The feedback_url of this Feedback.  # noqa: E501
        :type feedback_url: FeedbackUrl
        """
        self.swagger_types = {
            'feedback_form': FeedbackForm,
            'feedback_url': FeedbackUrl
        }

        self.attribute_map = {
            'feedback_form': 'feedback_form',
            'feedback_url': 'feedback_url'
        }
        self._feedback_form = feedback_form
        self._feedback_url = feedback_url

    @classmethod
    def from_dict(cls, dikt) -> 'Feedback':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Feedback of this Feedback.  # noqa: E501
        :rtype: Feedback
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feedback_form(self) -> FeedbackForm:
        """Gets the feedback_form of this Feedback.


        :return: The feedback_form of this Feedback.
        :rtype: FeedbackForm
        """
        return self._feedback_form

    @feedback_form.setter
    def feedback_form(self, feedback_form: FeedbackForm):
        """Sets the feedback_form of this Feedback.


        :param feedback_form: The feedback_form of this Feedback.
        :type feedback_form: FeedbackForm
        """

        self._feedback_form = feedback_form

    @property
    def feedback_url(self) -> FeedbackUrl:
        """Gets the feedback_url of this Feedback.


        :return: The feedback_url of this Feedback.
        :rtype: FeedbackUrl
        """
        return self._feedback_url

    @feedback_url.setter
    def feedback_url(self, feedback_url: FeedbackUrl):
        """Sets the feedback_url of this Feedback.


        :param feedback_url: The feedback_url of this Feedback.
        :type feedback_url: FeedbackUrl
        """

        self._feedback_url = feedback_url
