# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.context import Context  # noqa: F401,E501
from models.feedback import Feedback  # noqa: F401,E501


class FeedbackFormBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, context: Context=None, message: Feedback=None):  # noqa: E501
        """FeedbackFormBody - a model defined in Swagger

        :param context: The context of this FeedbackFormBody.  # noqa: E501
        :type context: Context
        :param message: The message of this FeedbackFormBody.  # noqa: E501
        :type message: Feedback
        """
        self.swagger_types = {
            'context': Context,
            'message': Feedback
        }

        self.attribute_map = {
            'context': 'context',
            'message': 'message'
        }
        self._context = context
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'FeedbackFormBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The feedback_form_body of this FeedbackFormBody.  # noqa: E501
        :rtype: FeedbackFormBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context(self) -> Context:
        """Gets the context of this FeedbackFormBody.


        :return: The context of this FeedbackFormBody.
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context: Context):
        """Sets the context of this FeedbackFormBody.


        :param context: The context of this FeedbackFormBody.
        :type context: Context
        """

        self._context = context

    @property
    def message(self) -> Feedback:
        """Gets the message of this FeedbackFormBody.


        :return: The message of this FeedbackFormBody.
        :rtype: Feedback
        """
        return self._message

    @message.setter
    def message(self, message: Feedback):
        """Sets the message of this FeedbackFormBody.


        :param message: The message of this FeedbackFormBody.
        :type message: Feedback
        """

        self._message = message
