# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model


class FeedbackUrlParams(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, feedback_id: str=None):  # noqa: E501
        """FeedbackUrlParams - a model defined in Swagger

        :param feedback_id: The feedback_id of this FeedbackUrlParams.  # noqa: E501
        :type feedback_id: str
        """
        self.swagger_types = {
            'feedback_id': str
        }

        self.attribute_map = {
            'feedback_id': 'feedback_id'
        }
        self._feedback_id = feedback_id

    @classmethod
    def from_dict(cls, dikt) -> 'FeedbackUrlParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FeedbackUrl_params of this FeedbackUrlParams.  # noqa: E501
        :rtype: FeedbackUrlParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feedback_id(self) -> str:
        """Gets the feedback_id of this FeedbackUrlParams.

        This value will be placed in the the $feedback_id url param in case of http/get and in the requestBody http/post requests  # noqa: E501

        :return: The feedback_id of this FeedbackUrlParams.
        :rtype: str
        """
        return self._feedback_id

    @feedback_id.setter
    def feedback_id(self, feedback_id: str):
        """Sets the feedback_id of this FeedbackUrlParams.

        This value will be placed in the the $feedback_id url param in case of http/get and in the requestBody http/post requests  # noqa: E501

        :param feedback_id: The feedback_id of this FeedbackUrlParams.
        :type feedback_id: str
        """
        if feedback_id is None:
            raise ValueError("Invalid value for `feedback_id`, must not be `None`")  # noqa: E501

        self._feedback_id = feedback_id
