# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.context import Context  # noqa: F401,E501
from models.get_feedback_form_message import GetFeedbackFormMessage  # noqa: F401,E501


class GetFeedbackFormBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, context: Context=None, message: GetFeedbackFormMessage=None):  # noqa: E501
        """GetFeedbackFormBody - a model defined in Swagger

        :param context: The context of this GetFeedbackFormBody.  # noqa: E501
        :type context: Context
        :param message: The message of this GetFeedbackFormBody.  # noqa: E501
        :type message: GetFeedbackFormMessage
        """
        self.swagger_types = {
            'context': Context,
            'message': GetFeedbackFormMessage
        }

        self.attribute_map = {
            'context': 'context',
            'message': 'message'
        }
        self._context = context
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'GetFeedbackFormBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_feedback_form_body of this GetFeedbackFormBody.  # noqa: E501
        :rtype: GetFeedbackFormBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context(self) -> Context:
        """Gets the context of this GetFeedbackFormBody.


        :return: The context of this GetFeedbackFormBody.
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context: Context):
        """Sets the context of this GetFeedbackFormBody.


        :param context: The context of this GetFeedbackFormBody.
        :type context: Context
        """

        self._context = context

    @property
    def message(self) -> GetFeedbackFormMessage:
        """Gets the message of this GetFeedbackFormBody.


        :return: The message of this GetFeedbackFormBody.
        :rtype: GetFeedbackFormMessage
        """
        return self._message

    @message.setter
    def message(self, message: GetFeedbackFormMessage):
        """Sets the message of this GetFeedbackFormBody.


        :param message: The message of this GetFeedbackFormBody.
        :type message: GetFeedbackFormMessage
        """

        self._message = message
