# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.context import Context  # noqa: F401,E501


class GetRatingCategoriesBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, context: Context=None):  # noqa: E501
        """GetRatingCategoriesBody - a model defined in Swagger

        :param context: The context of this GetRatingCategoriesBody.  # noqa: E501
        :type context: Context
        """
        self.swagger_types = {
            'context': Context
        }

        self.attribute_map = {
            'context': 'context'
        }
        self._context = context

    @classmethod
    def from_dict(cls, dikt) -> 'GetRatingCategoriesBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_rating_categories_body of this GetRatingCategoriesBody.  # noqa: E501
        :rtype: GetRatingCategoriesBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context(self) -> Context:
        """Gets the context of this GetRatingCategoriesBody.


        :return: The context of this GetRatingCategoriesBody.
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context: Context):
        """Sets the context of this GetRatingCategoriesBody.


        :param context: The context of this GetRatingCategoriesBody.
        :type context: Context
        """

        self._context = context
