# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models import RatingpropertiesratingCategory  # noqa: F401,E501
from models import str  # noqa: F401,E501


class GetFeedbackFormMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, rating_value: str=None, rating_category: RatingpropertiesratingCategory=None):  # noqa: E501
        """GetFeedbackFormMessage - a model defined in Swagger

        :param rating_value: The rating_value of this GetFeedbackFormMessage.  # noqa: E501
        :type rating_value: str
        :param rating_category: The rating_category of this GetFeedbackFormMessage.  # noqa: E501
        :type rating_category: RatingpropertiesratingCategory
        """
        self.swagger_types = {
            'rating_value': str,
            'rating_category': RatingpropertiesratingCategory
        }

        self.attribute_map = {
            'rating_value': 'rating_value',
            'rating_category': 'rating_category'
        }
        self._rating_value = rating_value
        self._rating_category = rating_category

    @classmethod
    def from_dict(cls, dikt) -> 'GetFeedbackFormMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_feedback_form_message of this GetFeedbackFormMessage.  # noqa: E501
        :rtype: GetFeedbackFormMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rating_value(self) -> str:
        """Gets the rating_value of this GetFeedbackFormMessage.


        :return: The rating_value of this GetFeedbackFormMessage.
        :rtype: str
        """
        return self._rating_value

    @rating_value.setter
    def rating_value(self, rating_value: str):
        """Sets the rating_value of this GetFeedbackFormMessage.


        :param rating_value: The rating_value of this GetFeedbackFormMessage.
        :type rating_value: str
        """

        self._rating_value = rating_value

    @property
    def rating_category(self) -> RatingpropertiesratingCategory:
        """Gets the rating_category of this GetFeedbackFormMessage.


        :return: The rating_category of this GetFeedbackFormMessage.
        :rtype: RatingpropertiesratingCategory
        """
        return self._rating_category

    @rating_category.setter
    def rating_category(self, rating_category: RatingpropertiesratingCategory):
        """Sets the rating_category of this GetFeedbackFormMessage.


        :param rating_category: The rating_category of this GetFeedbackFormMessage.
        :type rating_category: RatingpropertiesratingCategory
        """

        self._rating_category = rating_category
