# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.error import Error  # noqa: F401,E501
from models.inline_response200_message import InlineResponse200Message  # noqa: F401,E501


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: InlineResponse200Message=None, error: Error=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param message: The message of this InlineResponse2001.  # noqa: E501
        :type message: InlineResponse200Message
        :param error: The error of this InlineResponse2001.  # noqa: E501
        :type error: Error
        """
        self.swagger_types = {
            'message': InlineResponse200Message,
            'error': Error
        }

        self.attribute_map = {
            'message': 'message',
            'error': 'error'
        }
        self._message = message
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> InlineResponse200Message:
        """Gets the message of this InlineResponse2001.


        :return: The message of this InlineResponse2001.
        :rtype: InlineResponse200Message
        """
        return self._message

    @message.setter
    def message(self, message: InlineResponse200Message):
        """Sets the message of this InlineResponse2001.


        :param message: The message of this InlineResponse2001.
        :type message: InlineResponse200Message
        """

        self._message = message

    @property
    def error(self) -> Error:
        """Gets the error of this InlineResponse2001.


        :return: The error of this InlineResponse2001.
        :rtype: Error
        """
        return self._error

    @error.setter
    def error(self, error: Error):
        """Sets the error of this InlineResponse2001.


        :param error: The error of this InlineResponse2001.
        :type error: Error
        """

        self._error = error
