# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.ack import Ack  # noqa: F401,E501
from models.base_model_ import Model


class InlineResponse200Message(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ack: Ack=None):  # noqa: E501
        """InlineResponse200Message - a model defined in Swagger

        :param ack: The ack of this InlineResponse200Message.  # noqa: E501
        :type ack: Ack
        """
        self.swagger_types = {
            'ack': Ack
        }

        self.attribute_map = {
            'ack': 'ack'
        }
        self._ack = ack

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Message':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_message of this InlineResponse200Message.  # noqa: E501
        :rtype: InlineResponse200Message
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ack(self) -> Ack:
        """Gets the ack of this InlineResponse200Message.


        :return: The ack of this InlineResponse200Message.
        :rtype: Ack
        """
        return self._ack

    @ack.setter
    def ack(self, ack: Ack):
        """Sets the ack of this InlineResponse200Message.


        :param ack: The ack of this InlineResponse200Message.
        :type ack: Ack
        """
        if ack is None:
            raise ValueError("Invalid value for `ack`, must not be `None`")  # noqa: E501

        self._ack = ack
