# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model


class Language(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: str=None):  # noqa: E501
        """Language - a model defined in Swagger

        :param code: The code of this Language.  # noqa: E501
        :type code: str
        """
        self.swagger_types = {
            'code': str
        }

        self.attribute_map = {
            'code': 'code'
        }
        self._code = code

    @classmethod
    def from_dict(cls, dikt) -> 'Language':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Language of this Language.  # noqa: E501
        :rtype: Language
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this Language.


        :return: The code of this Language.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Language.


        :param code: The code of this Language.
        :type code: str
        """

        self._code = code
