# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.descriptor import Descriptor  # noqa: F401,E501
from models.time import Time  # noqa: F401,E501


class Offer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, descriptor: Descriptor=None, location_ids: List[str]=None, category_ids: List[str]=None, item_ids: List[str]=None, time: Time=None):  # noqa: E501
        """Offer - a model defined in Swagger

        :param id: The id of this Offer.  # noqa: E501
        :type id: str
        :param descriptor: The descriptor of this Offer.  # noqa: E501
        :type descriptor: Descriptor
        :param location_ids: The location_ids of this Offer.  # noqa: E501
        :type location_ids: List[str]
        :param category_ids: The category_ids of this Offer.  # noqa: E501
        :type category_ids: List[str]
        :param item_ids: The item_ids of this Offer.  # noqa: E501
        :type item_ids: List[str]
        :param time: The time of this Offer.  # noqa: E501
        :type time: Time
        """
        self.swagger_types = {
            'id': str,
            'descriptor': Descriptor,
            'location_ids': List[str],
            'category_ids': List[str],
            'item_ids': List[str],
            'time': Time
        }

        self.attribute_map = {
            'id': 'id',
            'descriptor': 'descriptor',
            'location_ids': 'location_ids',
            'category_ids': 'category_ids',
            'item_ids': 'item_ids',
            'time': 'time'
        }
        self._id = id
        self._descriptor = descriptor
        self._location_ids = location_ids
        self._category_ids = category_ids
        self._item_ids = item_ids
        self._time = time

    @classmethod
    def from_dict(cls, dikt) -> 'Offer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Offer of this Offer.  # noqa: E501
        :rtype: Offer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Offer.


        :return: The id of this Offer.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Offer.


        :param id: The id of this Offer.
        :type id: str
        """

        self._id = id

    @property
    def descriptor(self) -> Descriptor:
        """Gets the descriptor of this Offer.


        :return: The descriptor of this Offer.
        :rtype: Descriptor
        """
        return self._descriptor

    @descriptor.setter
    def descriptor(self, descriptor: Descriptor):
        """Sets the descriptor of this Offer.


        :param descriptor: The descriptor of this Offer.
        :type descriptor: Descriptor
        """

        self._descriptor = descriptor

    @property
    def location_ids(self) -> List[str]:
        """Gets the location_ids of this Offer.


        :return: The location_ids of this Offer.
        :rtype: List[str]
        """
        return self._location_ids

    @location_ids.setter
    def location_ids(self, location_ids: List[str]):
        """Sets the location_ids of this Offer.


        :param location_ids: The location_ids of this Offer.
        :type location_ids: List[str]
        """

        self._location_ids = location_ids

    @property
    def category_ids(self) -> List[str]:
        """Gets the category_ids of this Offer.


        :return: The category_ids of this Offer.
        :rtype: List[str]
        """
        return self._category_ids

    @category_ids.setter
    def category_ids(self, category_ids: List[str]):
        """Sets the category_ids of this Offer.


        :param category_ids: The category_ids of this Offer.
        :type category_ids: List[str]
        """

        self._category_ids = category_ids

    @property
    def item_ids(self) -> List[str]:
        """Gets the item_ids of this Offer.


        :return: The item_ids of this Offer.
        :rtype: List[str]
        """
        return self._item_ids

    @item_ids.setter
    def item_ids(self, item_ids: List[str]):
        """Sets the item_ids of this Offer.


        :param item_ids: The item_ids of this Offer.
        :type item_ids: List[str]
        """

        self._item_ids = item_ids

    @property
    def time(self) -> Time:
        """Gets the time of this Offer.


        :return: The time of this Offer.
        :rtype: Time
        """
        return self._time

    @time.setter
    def time(self, time: Time):
        """Sets the time of this Offer.


        :param time: The time of this Offer.
        :type time: Time
        """

        self._time = time
