# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models import str  # noqa: F401,E501


class OnInitMessageOrderProviderLocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None):  # noqa: E501
        """OnInitMessageOrderProviderLocation - a model defined in Swagger

        :param id: The id of this OnInitMessageOrderProviderLocation.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'id': str
        }

        self.attribute_map = {
            'id': 'id'
        }
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'OnInitMessageOrderProviderLocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The on_init_message_order_provider_location of this OnInitMessageOrderProviderLocation.  # noqa: E501
        :rtype: OnInitMessageOrderProviderLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this OnInitMessageOrderProviderLocation.


        :return: The id of this OnInitMessageOrderProviderLocation.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this OnInitMessageOrderProviderLocation.


        :param id: The id of this OnInitMessageOrderProviderLocation.
        :type id: str
        """

        self._id = id
