# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.on_init_message_order import OnInitMessageOrder  # noqa: F401,E501


class OnInitMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order: OnInitMessageOrder=None):  # noqa: E501
        """OnInitMessage - a model defined in Swagger

        :param order: The order of this OnInitMessage.  # noqa: E501
        :type order: OnInitMessageOrder
        """
        self.swagger_types = {
            'order': OnInitMessageOrder
        }

        self.attribute_map = {
            'order': 'order'
        }
        self._order = order

    @classmethod
    def from_dict(cls, dikt) -> 'OnInitMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The on_init_message of this OnInitMessage.  # noqa: E501
        :rtype: OnInitMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order(self) -> OnInitMessageOrder:
        """Gets the order of this OnInitMessage.


        :return: The order of this OnInitMessage.
        :rtype: OnInitMessageOrder
        """
        return self._order

    @order.setter
    def order(self, order: OnInitMessageOrder):
        """Sets the order of this OnInitMessage.


        :param order: The order of this OnInitMessage.
        :type order: OnInitMessageOrder
        """
        if order is None:
            raise ValueError("Invalid value for `order`, must not be `None`")  # noqa: E501

        self._order = order
