# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models import Providerpropertiesid  # noqa: F401,E501


class OnInitMessageOrderProvider(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: Providerpropertiesid=None):  # noqa: E501
        """OnInitMessageOrderProvider - a model defined in Swagger

        :param id: The id of this OnInitMessageOrderProvider.  # noqa: E501
        :type id: Providerpropertiesid
        """
        self.swagger_types = {
            'id': Providerpropertiesid
        }

        self.attribute_map = {
            'id': 'id'
        }
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'OnInitMessageOrderProvider':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The on_init_message_order_provider of this OnInitMessageOrderProvider.  # noqa: E501
        :rtype: OnInitMessageOrderProvider
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> Providerpropertiesid:
        """Gets the id of this OnInitMessageOrderProvider.


        :return: The id of this OnInitMessageOrderProvider.
        :rtype: Providerpropertiesid
        """
        return self._id

    @id.setter
    def id(self, id: Providerpropertiesid):
        """Sets the id of this OnInitMessageOrderProvider.


        :param id: The id of this OnInitMessageOrderProvider.
        :type id: Providerpropertiesid
        """

        self._id = id
