# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models import AddOnpropertiesid  # noqa: F401,E501
from models.base_model_ import Model


class OnInitMessageOrderAddOns(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: AddOnpropertiesid=None):  # noqa: E501
        """OnInitMessageOrderAddOns - a model defined in Swagger

        :param id: The id of this OnInitMessageOrderAddOns.  # noqa: E501
        :type id: AddOnpropertiesid
        """
        self.swagger_types = {
            'id': AddOnpropertiesid
        }

        self.attribute_map = {
            'id': 'id'
        }
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'OnInitMessageOrderAddOns':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The on_init_message_order_add_ons of this OnInitMessageOrderAddOns.  # noqa: E501
        :rtype: OnInitMessageOrderAddOns
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> AddOnpropertiesid:
        """Gets the id of this OnInitMessageOrderAddOns.


        :return: The id of this OnInitMessageOrderAddOns.
        :rtype: AddOnpropertiesid
        """
        return self._id

    @id.setter
    def id(self, id: AddOnpropertiesid):
        """Sets the id of this OnInitMessageOrderAddOns.


        :param id: The id of this OnInitMessageOrderAddOns.
        :type id: AddOnpropertiesid
        """

        self._id = id
