# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models import Offerpropertiesid  # noqa: F401,E501


class OnInitMessageOrderOffers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: Offerpropertiesid=None):  # noqa: E501
        """OnInitMessageOrderOffers - a model defined in Swagger

        :param id: The id of this OnInitMessageOrderOffers.  # noqa: E501
        :type id: Offerpropertiesid
        """
        self.swagger_types = {
            'id': Offerpropertiesid
        }

        self.attribute_map = {
            'id': 'id'
        }
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'OnInitMessageOrderOffers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The on_init_message_order_offers of this OnInitMessageOrderOffers.  # noqa: E501
        :rtype: OnInitMessageOrderOffers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> Offerpropertiesid:
        """Gets the id of this OnInitMessageOrderOffers.


        :return: The id of this OnInitMessageOrderOffers.
        :rtype: Offerpropertiesid
        """
        return self._id

    @id.setter
    def id(self, id: Offerpropertiesid):
        """Sets the id of this OnInitMessageOrderOffers.


        :param id: The id of this OnInitMessageOrderOffers.
        :type id: Offerpropertiesid
        """

        self._id = id
