# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.catalog import Catalog  # noqa: F401,E501


class OnSearchMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, catalog: Catalog=None):  # noqa: E501
        """OnSearchMessage - a model defined in Swagger

        :param catalog: The catalog of this OnSearchMessage.  # noqa: E501
        :type catalog: Catalog
        """
        self.swagger_types = {
            'catalog': Catalog
        }

        self.attribute_map = {
            'catalog': 'catalog'
        }
        self._catalog = catalog

    @classmethod
    def from_dict(cls, dikt) -> 'OnSearchMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The on_search_message of this OnSearchMessage.  # noqa: E501
        :rtype: OnSearchMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def catalog(self) -> Catalog:
        """Gets the catalog of this OnSearchMessage.


        :return: The catalog of this OnSearchMessage.
        :rtype: Catalog
        """
        return self._catalog

    @catalog.setter
    def catalog(self, catalog: Catalog):
        """Sets the catalog of this OnSearchMessage.


        :param catalog: The catalog of this OnSearchMessage.
        :type catalog: Catalog
        """
        if catalog is None:
            raise ValueError("Invalid value for `catalog`, must not be `None`")  # noqa: E501

        self._catalog = catalog
