# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.context import Context  # noqa: F401,E501
from models.error import Error  # noqa: F401,E501
from models.on_track_message import OnTrackMessage  # noqa: F401,E501


class OnTrackBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, context: Context=None, message: OnTrackMessage=None, error: Error=None):  # noqa: E501
        """OnTrackBody - a model defined in Swagger

        :param context: The context of this OnTrackBody.  # noqa: E501
        :type context: Context
        :param message: The message of this OnTrackBody.  # noqa: E501
        :type message: OnTrackMessage
        :param error: The error of this OnTrackBody.  # noqa: E501
        :type error: Error
        """
        self.swagger_types = {
            'context': Context,
            'message': OnTrackMessage,
            'error': Error
        }

        self.attribute_map = {
            'context': 'context',
            'message': 'message',
            'error': 'error'
        }
        self._context = context
        self._message = message
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'OnTrackBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The on_track_body of this OnTrackBody.  # noqa: E501
        :rtype: OnTrackBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context(self) -> Context:
        """Gets the context of this OnTrackBody.


        :return: The context of this OnTrackBody.
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context: Context):
        """Sets the context of this OnTrackBody.


        :param context: The context of this OnTrackBody.
        :type context: Context
        """
        if context is None:
            raise ValueError("Invalid value for `context`, must not be `None`")  # noqa: E501

        self._context = context

    @property
    def message(self) -> OnTrackMessage:
        """Gets the message of this OnTrackBody.


        :return: The message of this OnTrackBody.
        :rtype: OnTrackMessage
        """
        return self._message

    @message.setter
    def message(self, message: OnTrackMessage):
        """Sets the message of this OnTrackBody.


        :param message: The message of this OnTrackBody.
        :type message: OnTrackMessage
        """

        self._message = message

    @property
    def error(self) -> Error:
        """Gets the error of this OnTrackBody.


        :return: The error of this OnTrackBody.
        :rtype: Error
        """
        return self._error

    @error.setter
    def error(self, error: Error):
        """Sets the error of this OnTrackBody.


        :param error: The error of this OnTrackBody.
        :type error: Error
        """

        self._error = error
