# coding: utf-8

from __future__ import absolute_import

import re  # noqa: F401,E501
from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.image import Image  # noqa: F401,E501
from models.name import Name  # noqa: F401,E501
from models.operator_experience import OperatorExperience  # noqa: F401,E501
from models.person import Person  # noqa: F401,E501
from models.tags import Tags  # noqa: F401,E501


class Operator(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: Name=None, image: Image=None, dob: date=None, gender: str=None, cred: str=None, tags: Tags=None, experience: OperatorExperience=None):  # noqa: E501
        """Operator - a model defined in Swagger

        :param name: The name of this Operator.  # noqa: E501
        :type name: Name
        :param image: The image of this Operator.  # noqa: E501
        :type image: Image
        :param dob: The dob of this Operator.  # noqa: E501
        :type dob: date
        :param gender: The gender of this Operator.  # noqa: E501
        :type gender: str
        :param cred: The cred of this Operator.  # noqa: E501
        :type cred: str
        :param tags: The tags of this Operator.  # noqa: E501
        :type tags: Tags
        :param experience: The experience of this Operator.  # noqa: E501
        :type experience: OperatorExperience
        """
        self.swagger_types = {
            'name': Name,
            'image': Image,
            'dob': date,
            'gender': str,
            'cred': str,
            'tags': Tags,
            'experience': OperatorExperience
        }

        self.attribute_map = {
            'name': 'name',
            'image': 'image',
            'dob': 'dob',
            'gender': 'gender',
            'cred': 'cred',
            'tags': 'tags',
            'experience': 'experience'
        }
        self._name = name
        self._image = image
        self._dob = dob
        self._gender = gender
        self._cred = cred
        self._tags = tags
        self._experience = experience

    @classmethod
    def from_dict(cls, dikt) -> 'Operator':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Operator of this Operator.  # noqa: E501
        :rtype: Operator
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> Name:
        """Gets the name of this Operator.


        :return: The name of this Operator.
        :rtype: Name
        """
        return self._name

    @name.setter
    def name(self, name: Name):
        """Sets the name of this Operator.


        :param name: The name of this Operator.
        :type name: Name
        """

        self._name = name

    @property
    def image(self) -> Image:
        """Gets the image of this Operator.


        :return: The image of this Operator.
        :rtype: Image
        """
        return self._image

    @image.setter
    def image(self, image: Image):
        """Sets the image of this Operator.


        :param image: The image of this Operator.
        :type image: Image
        """

        self._image = image

    @property
    def dob(self) -> date:
        """Gets the dob of this Operator.


        :return: The dob of this Operator.
        :rtype: date
        """
        return self._dob

    @dob.setter
    def dob(self, dob: date):
        """Sets the dob of this Operator.


        :param dob: The dob of this Operator.
        :type dob: date
        """

        self._dob = dob

    @property
    def gender(self) -> str:
        """Gets the gender of this Operator.

        Gender of something, typically a Person, but possibly also fictional characters, animals, etc. While Male and Female may be used, text strings are also acceptable for people who do not identify as a binary gender  # noqa: E501

        :return: The gender of this Operator.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """Sets the gender of this Operator.

        Gender of something, typically a Person, but possibly also fictional characters, animals, etc. While Male and Female may be used, text strings are also acceptable for people who do not identify as a binary gender  # noqa: E501

        :param gender: The gender of this Operator.
        :type gender: str
        """

        self._gender = gender

    @property
    def cred(self) -> str:
        """Gets the cred of this Operator.


        :return: The cred of this Operator.
        :rtype: str
        """
        return self._cred

    @cred.setter
    def cred(self, cred: str):
        """Sets the cred of this Operator.


        :param cred: The cred of this Operator.
        :type cred: str
        """

        self._cred = cred

    @property
    def tags(self) -> Tags:
        """Gets the tags of this Operator.


        :return: The tags of this Operator.
        :rtype: Tags
        """
        return self._tags

    @tags.setter
    def tags(self, tags: Tags):
        """Sets the tags of this Operator.


        :param tags: The tags of this Operator.
        :type tags: Tags
        """

        self._tags = tags

    @property
    def experience(self) -> OperatorExperience:
        """Gets the experience of this Operator.


        :return: The experience of this Operator.
        :rtype: OperatorExperience
        """
        return self._experience

    @experience.setter
    def experience(self, experience: OperatorExperience):
        """Sets the experience of this Operator.


        :param experience: The experience of this Operator.
        :type experience: OperatorExperience
        """

        self._experience = experience
