# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model


class Organization(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, cred: str=None):  # noqa: E501
        """Organization - a model defined in Swagger

        :param name: The name of this Organization.  # noqa: E501
        :type name: str
        :param cred: The cred of this Organization.  # noqa: E501
        :type cred: str
        """
        self.swagger_types = {
            'name': str,
            'cred': str
        }

        self.attribute_map = {
            'name': 'name',
            'cred': 'cred'
        }
        self._name = name
        self._cred = cred

    @classmethod
    def from_dict(cls, dikt) -> 'Organization':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Organization of this Organization.  # noqa: E501
        :rtype: Organization
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Organization.


        :return: The name of this Organization.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Organization.


        :param name: The name of this Organization.
        :type name: str
        """

        self._name = name

    @property
    def cred(self) -> str:
        """Gets the cred of this Organization.


        :return: The cred of this Organization.
        :rtype: str
        """
        return self._cred

    @cred.setter
    def cred(self, cred: str):
        """Sets the cred of this Organization.


        :param cred: The cred of this Organization.
        :type cred: str
        """

        self._cred = cred
