# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.context import Context  # noqa: F401,E501
from models import RatingpropertiesratingCategory  # noqa: F401,E501


class RatingCategoriesBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, context: Context=None, rating_categories: List[RatingpropertiesratingCategory]=None):  # noqa: E501
        """RatingCategoriesBody - a model defined in Swagger

        :param context: The context of this RatingCategoriesBody.  # noqa: E501
        :type context: Context
        :param rating_categories: The rating_categories of this RatingCategoriesBody.  # noqa: E501
        :type rating_categories: List[RatingpropertiesratingCategory]
        """
        self.swagger_types = {
            'context': Context,
            'rating_categories': List[RatingpropertiesratingCategory]
        }

        self.attribute_map = {
            'context': 'context',
            'rating_categories': 'rating_categories'
        }
        self._context = context
        self._rating_categories = rating_categories

    @classmethod
    def from_dict(cls, dikt) -> 'RatingCategoriesBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The rating_categories_body of this RatingCategoriesBody.  # noqa: E501
        :rtype: RatingCategoriesBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context(self) -> Context:
        """Gets the context of this RatingCategoriesBody.


        :return: The context of this RatingCategoriesBody.
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context: Context):
        """Sets the context of this RatingCategoriesBody.


        :param context: The context of this RatingCategoriesBody.
        :type context: Context
        """

        self._context = context

    @property
    def rating_categories(self) -> List[RatingpropertiesratingCategory]:
        """Gets the rating_categories of this RatingCategoriesBody.


        :return: The rating_categories of this RatingCategoriesBody.
        :rtype: List[RatingpropertiesratingCategory]
        """
        return self._rating_categories

    @rating_categories.setter
    def rating_categories(self, rating_categories: List[RatingpropertiesratingCategory]):
        """Sets the rating_categories of this RatingCategoriesBody.


        :param rating_categories: The rating_categories of this RatingCategoriesBody.
        :type rating_categories: List[RatingpropertiesratingCategory]
        """

        self._rating_categories = rating_categories
