# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.context import Context  # noqa: F401,E501
from models.option import Option  # noqa: F401,E501


class ReturnReasonsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, context: Context=None, return_reasons: List[Option]=None):  # noqa: E501
        """ReturnReasonsBody - a model defined in Swagger

        :param context: The context of this ReturnReasonsBody.  # noqa: E501
        :type context: Context
        :param return_reasons: The return_reasons of this ReturnReasonsBody.  # noqa: E501
        :type return_reasons: List[Option]
        """
        self.swagger_types = {
            'context': Context,
            'return_reasons': List[Option]
        }

        self.attribute_map = {
            'context': 'context',
            'return_reasons': 'return_reasons'
        }
        self._context = context
        self._return_reasons = return_reasons

    @classmethod
    def from_dict(cls, dikt) -> 'ReturnReasonsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The return_reasons_body of this ReturnReasonsBody.  # noqa: E501
        :rtype: ReturnReasonsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context(self) -> Context:
        """Gets the context of this ReturnReasonsBody.


        :return: The context of this ReturnReasonsBody.
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context: Context):
        """Sets the context of this ReturnReasonsBody.


        :param context: The context of this ReturnReasonsBody.
        :type context: Context
        """

        self._context = context

    @property
    def return_reasons(self) -> List[Option]:
        """Gets the return_reasons of this ReturnReasonsBody.


        :return: The return_reasons of this ReturnReasonsBody.
        :rtype: List[Option]
        """
        return self._return_reasons

    @return_reasons.setter
    def return_reasons(self, return_reasons: List[Option]):
        """Sets the return_reasons of this ReturnReasonsBody.


        :param return_reasons: The return_reasons of this ReturnReasonsBody.
        :type return_reasons: List[Option]
        """

        self._return_reasons = return_reasons
