# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.duration import Duration  # noqa: F401,E501


class Schedule(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, frequency: Duration=None, holidays: List[datetime]=None, times: List[datetime]=None):  # noqa: E501
        """Schedule - a model defined in Swagger

        :param frequency: The frequency of this Schedule.  # noqa: E501
        :type frequency: Duration
        :param holidays: The holidays of this Schedule.  # noqa: E501
        :type holidays: List[datetime]
        :param times: The times of this Schedule.  # noqa: E501
        :type times: List[datetime]
        """
        self.swagger_types = {
            'frequency': Duration,
            'holidays': List[datetime],
            'times': List[datetime]
        }

        self.attribute_map = {
            'frequency': 'frequency',
            'holidays': 'holidays',
            'times': 'times'
        }
        self._frequency = frequency
        self._holidays = holidays
        self._times = times

    @classmethod
    def from_dict(cls, dikt) -> 'Schedule':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Schedule of this Schedule.  # noqa: E501
        :rtype: Schedule
        """
        return util.deserialize_model(dikt, cls)

    @property
    def frequency(self) -> Duration:
        """Gets the frequency of this Schedule.


        :return: The frequency of this Schedule.
        :rtype: Duration
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency: Duration):
        """Sets the frequency of this Schedule.


        :param frequency: The frequency of this Schedule.
        :type frequency: Duration
        """

        self._frequency = frequency

    @property
    def holidays(self) -> List[datetime]:
        """Gets the holidays of this Schedule.


        :return: The holidays of this Schedule.
        :rtype: List[datetime]
        """
        return self._holidays

    @holidays.setter
    def holidays(self, holidays: List[datetime]):
        """Sets the holidays of this Schedule.


        :param holidays: The holidays of this Schedule.
        :type holidays: List[datetime]
        """

        self._holidays = holidays

    @property
    def times(self) -> List[datetime]:
        """Gets the times of this Schedule.


        :return: The times of this Schedule.
        :rtype: List[datetime]
        """
        return self._times

    @times.setter
    def times(self, times: List[datetime]):
        """Sets the times of this Schedule.


        :param times: The times of this Schedule.
        :type times: List[datetime]
        """

        self._times = times
