# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.intent import Intent  # noqa: F401,E501


class SearchMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, intent: Intent=None):  # noqa: E501
        """SearchMessage - a model defined in Swagger

        :param intent: The intent of this SearchMessage.  # noqa: E501
        :type intent: Intent
        """
        self.swagger_types = {
            'intent': Intent
        }

        self.attribute_map = {
            'intent': 'intent'
        }
        self._intent = intent

    @classmethod
    def from_dict(cls, dikt) -> 'SearchMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The search_message of this SearchMessage.  # noqa: E501
        :rtype: SearchMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def intent(self) -> Intent:
        """Gets the intent of this SearchMessage.


        :return: The intent of this SearchMessage.
        :rtype: Intent
        """
        return self._intent

    @intent.setter
    def intent(self, intent: Intent):
        """Sets the intent of this SearchMessage.


        :param intent: The intent of this SearchMessage.
        :type intent: Intent
        """

        self._intent = intent
