# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.order import Order  # noqa: F401,E501


class SelectMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order: Order=None):  # noqa: E501
        """SelectMessage - a model defined in Swagger

        :param order: The order of this SelectMessage.  # noqa: E501
        :type order: Order
        """
        self.swagger_types = {
            'order': Order
        }

        self.attribute_map = {
            'order': 'order'
        }
        self._order = order

    @classmethod
    def from_dict(cls, dikt) -> 'SelectMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The select_message of this SelectMessage.  # noqa: E501
        :rtype: SelectMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order(self) -> Order:
        """Gets the order of this SelectMessage.


        :return: The order of this SelectMessage.
        :rtype: Order
        """
        return self._order

    @order.setter
    def order(self, order: Order):
        """Sets the order of this SelectMessage.


        :param order: The order of this SelectMessage.
        :type order: Order
        """
        if order is None:
            raise ValueError("Invalid value for `order`, must not be `None`")  # noqa: E501

        self._order = order
