# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models import Orderpropertiesid  # noqa: F401,E501


class StatusMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order_id: Orderpropertiesid=None):  # noqa: E501
        """StatusMessage - a model defined in Swagger

        :param order_id: The order_id of this StatusMessage.  # noqa: E501
        :type order_id: Orderpropertiesid
        """
        self.swagger_types = {
            'order_id': Orderpropertiesid
        }

        self.attribute_map = {
            'order_id': 'order_id'
        }
        self._order_id = order_id

    @classmethod
    def from_dict(cls, dikt) -> 'StatusMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The status_message of this StatusMessage.  # noqa: E501
        :rtype: StatusMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> Orderpropertiesid:
        """Gets the order_id of this StatusMessage.


        :return: The order_id of this StatusMessage.
        :rtype: Orderpropertiesid
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: Orderpropertiesid):
        """Sets the order_id of this StatusMessage.


        :param order_id: The order_id of this StatusMessage.
        :type order_id: Orderpropertiesid
        """
        if order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id
