# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model


class SupportMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ref_id: str=None):  # noqa: E501
        """SupportMessage - a model defined in Swagger

        :param ref_id: The ref_id of this SupportMessage.  # noqa: E501
        :type ref_id: str
        """
        self.swagger_types = {
            'ref_id': str
        }

        self.attribute_map = {
            'ref_id': 'ref_id'
        }
        self._ref_id = ref_id

    @classmethod
    def from_dict(cls, dikt) -> 'SupportMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The support_message of this SupportMessage.  # noqa: E501
        :rtype: SupportMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ref_id(self) -> str:
        """Gets the ref_id of this SupportMessage.

        ID of the element for which support is needed  # noqa: E501

        :return: The ref_id of this SupportMessage.
        :rtype: str
        """
        return self._ref_id

    @ref_id.setter
    def ref_id(self, ref_id: str):
        """Sets the ref_id of this SupportMessage.

        ID of the element for which support is needed  # noqa: E501

        :param ref_id: The ref_id of this SupportMessage.
        :type ref_id: str
        """

        self._ref_id = ref_id
