# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models import Orderpropertiesid  # noqa: F401,E501


class TrackMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order_id: Orderpropertiesid=None, callback_url: str=None):  # noqa: E501
        """TrackMessage - a model defined in Swagger

        :param order_id: The order_id of this TrackMessage.  # noqa: E501
        :type order_id: Orderpropertiesid
        :param callback_url: The callback_url of this TrackMessage.  # noqa: E501
        :type callback_url: str
        """
        self.swagger_types = {
            'order_id': Orderpropertiesid,
            'callback_url': str
        }

        self.attribute_map = {
            'order_id': 'order_id',
            'callback_url': 'callback_url'
        }
        self._order_id = order_id
        self._callback_url = callback_url

    @classmethod
    def from_dict(cls, dikt) -> 'TrackMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The track_message of this TrackMessage.  # noqa: E501
        :rtype: TrackMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> Orderpropertiesid:
        """Gets the order_id of this TrackMessage.


        :return: The order_id of this TrackMessage.
        :rtype: Orderpropertiesid
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: Orderpropertiesid):
        """Sets the order_id of this TrackMessage.


        :param order_id: The order_id of this TrackMessage.
        :type order_id: Orderpropertiesid
        """
        if order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id

    @property
    def callback_url(self) -> str:
        """Gets the callback_url of this TrackMessage.


        :return: The callback_url of this TrackMessage.
        :rtype: str
        """
        return self._callback_url

    @callback_url.setter
    def callback_url(self, callback_url: str):
        """Sets the callback_url of this TrackMessage.


        :param callback_url: The callback_url of this TrackMessage.
        :type callback_url: str
        """

        self._callback_url = callback_url
