# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import List, Dict  # noqa: F401

from models import util
from models.base_model_ import Model
from models.order import Order  # noqa: F401,E501


class UpdateMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, update_target: str=None, order: Order=None):  # noqa: E501
        """UpdateMessage - a model defined in Swagger

        :param update_target: The update_target of this UpdateMessage.  # noqa: E501
        :type update_target: str
        :param order: The order of this UpdateMessage.  # noqa: E501
        :type order: Order
        """
        self.swagger_types = {
            'update_target': str,
            'order': Order
        }

        self.attribute_map = {
            'update_target': 'update_target',
            'order': 'order'
        }
        self._update_target = update_target
        self._order = order

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The update_message of this UpdateMessage.  # noqa: E501
        :rtype: UpdateMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def update_target(self) -> str:
        """Gets the update_target of this UpdateMessage.

        Comma separated values of order objects being updated. For example: ```\"update_target\":\"item,billing,fulfillment\"```  # noqa: E501

        :return: The update_target of this UpdateMessage.
        :rtype: str
        """
        return self._update_target

    @update_target.setter
    def update_target(self, update_target: str):
        """Sets the update_target of this UpdateMessage.

        Comma separated values of order objects being updated. For example: ```\"update_target\":\"item,billing,fulfillment\"```  # noqa: E501

        :param update_target: The update_target of this UpdateMessage.
        :type update_target: str
        """
        if update_target is None:
            raise ValueError("Invalid value for `update_target`, must not be `None`")  # noqa: E501

        self._update_target = update_target

    @property
    def order(self) -> Order:
        """Gets the order of this UpdateMessage.


        :return: The order of this UpdateMessage.
        :rtype: Order
        """
        return self._order

    @order.setter
    def order(self, order: Order):
        """Sets the order of this UpdateMessage.


        :param order: The order of this UpdateMessage.
        :type order: Order
        """
        if order is None:
            raise ValueError("Invalid value for `order`, must not be `None`")  # noqa: E501

        self._order = order
